# Generated by Django 5.2 on 2025-05-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_jobcarditem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='previous_scooter_status',
            field=models.CharField(blank=True, help_text='The status of the scooter before maintenance', max_length=20, null=True),
        ),
    ]
