# Generated by Django 5.2 on 2025-05-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='part_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='parts',
            unique_together={('part_number', 'store')},
        ),
    ]
