# Generated by Django 5.2 on 2025-05-05 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_parts_part_number_alter_parts_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parts',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
