# Generated by Django 5.2 on 2025-05-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_parts_current_stock_alter_parts_reorder_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scooter',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='License Number'),
        ),
    ]
