# Generated by Django 5.2 on 2025-05-08 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_supplier_purchase_purchaseitem_scooter_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='inventory.store'),
        ),
    ]
